apiVersion: v1
kind: Pod
metadata: 
    name: nginx
    labels: 
        run: nginx
spec:
    containers: 
      - image : nginx
        name: nginx
      - name: resource-container
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"